name: CFDI v3.2 - Publicar versión de desarrollo.

on:
  push:
    branches: [ master ]
    paths:
      - 'comprobantes/v3_2/**'

jobs:
  release-snapshot:
    name: Publicar versión snapshot.
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código.
        uses: actions/checkout@v2

      - name: Instalar Java 8.
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Publicar snapshot.
        run: mvn -s $GITHUB_WORKSPACE/settings.xml -B deploy -f comprobantes/v3_2/pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
