name: CFDI - Publicar versión de desarrollo.

on:
  push:
    branches: [ development ]

jobs:
  release-snapshot:
    name: Publicar versión snapshot.
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código.
        uses: actions/checkout@v2

      - name: Instalar Java 8.
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Publicar snapshot.
        run: mvn -s $GITHUB_WORKSPACE/settings.xml -B deploy -f cfdi-parent/pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
