name: CFDI - Pull request

on:
  pull_request:
    paths:
      - 'pom.xml'

jobs:
  verification:
    name: Verificación del proyecto padre.
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código.
        uses: actions/checkout@v2

      - name: Instalar Java 8.
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Caché de paquetes de Maven.
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Verificación.
        run: mvn -N -s $GITHUB_WORKSPACE/settings.xml -B verify -f cfdi-parent/pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
