name: Pruebas previas a integración.

on: pull_request

jobs:
  unit_tests:
    name: Ejecución de pruebas unitarias.
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código.
        uses: actions/checkout@v2

      - name: Instalar Java 8.
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Caché de paquetes de Maven.
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Verificación.
        run: mvn -B verify
