name: CFDI - Pull request.

on:
  pull_request:
    branches: [ development ]

jobs:
  unit-test:
    name: Ejecutar pruebas unitarias.
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código.
        uses: actions/checkout@v2

      - name: Instalar Java 8.
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Correr pruebas unitarias y verificación.
        run: mvn -B verify -f cfdi-parent/pom.xml
