# TODO update to deploy snapshots.
on: workflow_dispatch
  #pull_request:
  #  branches:
  #    - master

jobs:
  merga:
    name: No ni merga
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código.
        uses: actions/checkout@v2

      - name: Importar llave GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Instalar Java 8.
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      - name: Caché de paquetes de Maven.
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Publish package
        run: mvn install deploy -P release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}