name: CFDI - Liberación

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Esta versión
        required: true
      dev_version:
        description: Siguiente versión
        required: true

jobs:
  release_to_packages:
    name: Liberar a Github Packages.
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código.
        uses: actions/checkout@v2

      - name: Instalar Java 8.
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Caché de paquetes de Maven.
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configurar usuario de Git
        run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"

      - name: Preparar liberación
        run: mvn -B -s $GITHUB_WORKSPACE/settings.xml -f cfdi-parent/pom.xml release:prepare release:perform -DdevelopmentVersion=${{ github.event.inputs.dev_version }} -DreleaseVersion=${{ github.event.inputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
